In [ ]:
# Loaded variable 'df' from URI: /mnt/research/ATD/tensor_regression/experiments/synthetic/results/eg1-spltr_logreg_c4.csv
import pandas as pd

In [8]:
df = pd.read_csv(r'/mnt/research/ATD/tensor_regression/experiments/synthetic/results/eg1-spltr_logreg_c4.csv')
df.groupby(['Model','n_train']).mean()[['test_score','mean_val_score']]

                               test_score  mean_val_score
Model                 n_train
RidgeTucker           400        0.496000        0.587500
                      800        0.667000        0.695833
                      1600       0.836333        0.838542
                      3200       0.950333        0.953646
SparseRidgeTucker-1   400        0.526500        0.618750
                      800        0.673667        0.725000
                      1600       0.892667        0.896875
                      3200       0.958000        0.964583
SparseRidgeTucker-2   400        0.565000        0.612500
                      800        0.691333        0.745833
                      1600       0.904333        0.909375
                      3200       0.959000        0.968229
SparseRidgeTucker-3   400        0.565000        0.612500
                      800        0.691333        0.745833
                      1600       0.904333        0.909375
                      3200       0.959000        0.968229
Tucker                400        0.502500        0.481250
                      800        0.509000        0.502083
                      1600       0.658333        0.654167
                      3200       0.935000        0.932812
Vectorized-ElasticNet 400        0.545000        0.620833
                      800        0.564667        0.614583
                      1600       0.678000        0.690625
                      3200       0.782000        0.771875
Vectorized-Lasso      400        0.551667        0.608333
                      800        0.583667        0.637500
                      1600       0.661333        0.679167
                      3200       0.763000        0.754167
Vectorized-Ridge      400        0.512000        0.583333
                      800        0.528333        0.589583
                      1600       0.546667        0.575000
                      3200       0.586000        0.595833

In [11]:
df_c8 = pd.read_csv(r'/mnt/research/ATD/tensor_regression/experiments/synthetic/results/eg1-spltr_logreg_c8.csv')
# df_c8
df_c8.groupby(['Model','n_train']).mean()[['test_score','mean_val_score']]

                               test_score  mean_val_score
Model                 n_train
RidgeTucker           800          0.7000        0.712500
                      1600         0.8710        0.865625
                      3200         0.9510        0.950000
SparseRidgeTucker-1   800          0.7190        0.743750
                      1600         0.8785        0.871875
                      3200         0.9510        0.951562
SparseRidgeTucker-2   800          0.7190        0.768750
                      1600         0.8910        0.881250
                      3200         0.9510        0.951562
SparseRidgeTucker-3   800          0.7190        0.768750
                      1600         0.8910        0.881250
                      3200         0.9510        0.951562
Tucker                800          0.5050        0.468750
                      1600         0.7395        0.737500
                      3200         0.9410        0.943750
Vectorized-ElasticNet 400          0.5185        0.581250
                      800          0.5285        0.546875
                      1600         0.5610        0.571875
                      3200         0.6820        0.687500
Vectorized-Lasso      400          0.5220        0.568750
                      800          0.5070        0.553125
                      1600         0.5580        0.571875
                      3200         0.6270        0.676562
Vectorized-Ridge      400          0.5165        0.575000
                      800          0.5095        0.546875
                      1600         0.5590        0.562500
                      3200         0.5620        0.596875

In [ ]:
df_c16 = pd.read_csv(r'/mnt/research/ATD/tensor_regression/experiments/synthetic/results/eg1-spltr_logreg_c16.csv')
df_c16.groupby(['Model','n_train']).mean()[['test_score','mean_val_score']]

                               test_score  mean_val_score
Model                 n_train
RidgeTucker           400          0.5080        0.587500
                      800          0.6405        0.650000
                      1600         0.8815        0.873438
                      3200         0.9490        0.952344
SparseRidgeTucker-1   400          0.5110        0.631250
                      800          0.6700        0.668750
                      1600         0.8965        0.896875
                      3200         0.9545        0.954687
SparseRidgeTucker-2   400          0.5100        0.668750
                      800          0.6700        0.665625
                      1600         0.9015        0.901563
                      3200         0.9560        0.959375
SparseRidgeTucker-3   400          0.5100        0.668750
                      800          0.6700        0.665625
                      1600         0.9015        0.901563
                      3200         0.9560        0.959375
Tucker                400          0.4915        0.437500
                      800          0.5010        0.468750
                      1600         0.6600        0.635938
                      3200         0.9335        0.924219
Vectorized-ElasticNet 400          0.4890        0.550000
                      800          0.5010        0.562500
                      1600         0.5380        0.575000
                      3200         0.5965        0.592188
Vectorized-Lasso      400          0.4805        0.575000
                      800          0.5195        0.565625
                      1600         0.5480        0.579688
                      3200         0.5865        0.597656
Vectorized-Ridge      400          0.5030        0.525000
                      800          0.5170        0.546875
                      1600         0.5380        0.568750
                      3200         0.5785        0.585156